[project]
name = "parampacmap"
version = "0.1.1rc0"
description = "Package for Parameterized PaCMAP (ParamRepulsor)."
readme = "README.md"
url = "https://github.com/hyhuang00/ParamRepulsor"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers"
]
authors = [
    { name = "Haiyang Huang", email = "hyhuang@cs.duke.edu" },
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.20",
    "scikit-learn>=0.20",
    "torch>=2.0.0",
]

[project.optional-dependencies]
extras = [
    "pyyaml>=6.0.2",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython>=8.18.1",
    "pytest>=8.3.4",
    "pyyaml>=6.0.2",
]
